sudo: false

language: node_js

os:
  - linux
  # - osx

node_js:
  - node
  - 9
  - 8

cache:
  yarn: true
  directories:
    - node_modules

script:
  - node --version
  - yarn --version
  - yarn test

notifications:
  email: false
